### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by romainfrancois** [ThinkRstat/prenoms#10]
Par exemple (suggéré par @maelle)

Reprendre cet article avec les prénoms français
http://staff.math.su.se/hoehle/blog/2017/03/01/morebabynames.html

**Comment by mhoehle** [comment]
You might also want to check out: 

http://staff.math.su.se/hoehle/naming/ 

which contains the link to the github repository containing the code & pre-preprint of a recent article about baby names in the Significance magazine: http://onlinelibrary.wiley.com/doi/10.1111/j.1740-9713.2017.01037.x/abstract

Maybe this is helpful in any way...

**Comment by FlorenceMounier** [comment]
Not for the moment
