### ISSUE TITLE
picture in README does not include Cervan

### ISSUE THREAD

**Issue by ginolhac** [ThinkRstat/prenoms#11]
while the code does.
just saying,

cheers

**Comment by ColinFay** [comment]
This is due to the fact that Cervan is a rare name, and there is no record in the database: 

```
prenoms %>% filter(name == "Cervan")
# A tibble: 0 x 6
# ... with 6 variables: year <int>, sex <chr>, name <chr>, n <int>,
#   dpt <chr>, prop <dbl>
```

The INSEE doesn't register a name if there is less than 3 records for an observation (i.e less than 3 names for a given year/sex/dep)

**Comment by ginolhac** [comment]
sad, there should be at least 1 ;)

**Comment by cecilesauder** [comment]
> This is due to the fact that Cervan is a rare name, and there is no record in the database:
> 
> ```
> prenoms %>% filter(name == "Cervan")
> # A tibble: 0 x 6
> # ... with 6 variables: year <int>, sex <chr>, name <chr>, n <int>,
> #   dpt <chr>, prop <dbl>
> ```
> 
> The INSEE doesn't register a name if there is less than 3 records for an observation (i.e less than 3 names for a given year/sex/dep)

But it's horrible, you don't exist if there aren't at least two people with the same name as you! Thank you the INSEE
"Cervan" doesn't exist, but "A" does... -__-
